filebeat.inputs:
  - type: log
    enabled: true
    paths:
      - /app/logs/*.log 

processors:
  - add_host_metadata: ~
  - add_cloud_metadata: ~
  - add_docker_metadata: ~

output.elasticsearch:
  hosts: ["http://elasticsearch:9200"]

setup.kibana:
  host: "kibana:5601"

setup.template.enabled: true
setup.ilm.enabled: false

logging.level: info