services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.17.18
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
    volumes:
      - esdata:/usr/share/elasticsearch/data
    ports:
      - "${ELASTICSEARCH_EXTERNAL_PORT}:${ELASTICSEARCH_INTERNAL_PORT}"
    networks:
      - network-sentinel
    env_file:
      - .env

  logstash:
    image: docker.elastic.co/logstash/logstash:7.17.18
    container_name: logstash
    volumes:
      - ./logstash/config/logstash.yml:/usr/share/logstash/config/logstash.yml
      - ./logstash/pipeline:/usr/share/logstash/pipeline
      - ./sentinel-app/logs:/app/logs
    ports:
      - "${LOGSTASH_EXTERNAL_PORT_1}:${LOGSTASH_INTERNAL_PORT_1}"
      - "${LOGSTASH_EXTERNAL_PORT_2}:${LOGSTASH_INTERNAL_PORT_2}"
    depends_on:
      - elasticsearch
    networks:
      - network-sentinel
    env_file:
      - .env

  kibana:
    image: docker.elastic.co/kibana/kibana:7.17.18
    container_name: kibana
    ports:
      - "${KIBANA_EXTERNAL_PORT}:${KIBANA_EXTERNAL_PORT}"
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:${ELASTICSEARCH_EXTERNAL_PORT}
    depends_on:
      - elasticsearch
    networks:
      - network-sentinel
    env_file:
      - .env

  gateway:
    build:
      context: ./sentinel-app
    container_name: sentinel-app
    ports:
      - "${PORT}:${PORT}"
    volumes:
    - ./sentinel-app/logs:/app/logs
    networks:
      - network-sentinel
    env_file:
      - .env

  redis:
    image: redis:7.2.5
    container_name: redis
    ports:
      - "${REDIS_EXTERNAL_PORT}:${REDIS_INTERNAL_PORT}"
    volumes:
      - redisdata:/data
    networks:
      - network-sentinel
    env_file:
      - .env

  mongodb:
    image: mongo:6.0
    container_name: mongodb
    ports:
      - "${MONGODB_EXTERNAL_PORT}:${MONGODB_INTERNAL_PORT}"
    volumes:
      - mongodata:/data/db
    networks:
      - network-sentinel
    env_file:
      - .env
      
volumes:
  esdata:
  redisdata:
  mongodata:

networks:
  network-sentinel: